#!/usr/bin/env sh

# =========================================================================
#
# Simplify handling with the clipboard in BusyBox under Windows
#
# Do something with data taken from the clipboard
# clp | ...
#
# Do something with data and keep in the clipboard
# ... | clp
#
# =========================================================================

clp() {
	if [ "$1" = "-h" ]
	then
		echo "Usage: [ clp | ] ... [ | clp ]"
		return
	fi

	if [ ! -t 0 ]
	then
		# ... | clp
		clip
	else
		# clp | ...
		# or simply output the clipboard
		# sed is used here to get rid of the extra last line being
		# generated by powershell. However sed itself outputs
		# EOL even the last line is not terminated by EOL. It's
		# out of our power to change it because of sed design.
		powershell -NoLogo -NoProfile -Command Get-Clipboard \
		| sed '$ { /^\r*$/d }'
	fi

}

# =========================================================================

clp "$@"

# =========================================================================

#EOF
